pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                script {
                    sh './mvnw clean install' 
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    sh './mvnw test' 
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    deploy to AWS
                }
            }
        }
    }
}
